// Gerado automaticamente por excel_para_json.py
// NÃO editar à mão.
window.BANCO_DADOS = {
  "molde (2)": [
    {
      "nome": "mpindi",
      "condicao": "",
      "populacao": "pediatrica",
      "via": "im",
      "idade": "",
      "peso": "40;",
      "dose": "500 mg,1000 mg,500 mg,mg",
      "concentracao": "250 mg/5 ml|50",
      "intervalo": "ataque(12, 8)",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 1"
    },
    {
      "nome": "mpindi",
      "condicao": "",
      "populacao": "gravida",
      "via": "iv",
      "idade": "",
      "peso": "40;",
      "dose": "500 mg,1000 mg,500 mg,mg",
      "concentracao": "250 mg/5 ml|50",
      "intervalo": "8, 12",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 1"
    },
    {
      "nome": "Dip|nome",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": ";60",
      "dose": "15,30,15,mg",
      "concentracao": "2.5 g/5 ml|500",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 1"
    },],
  "msf": [
    {
      "nome": "Testesimples | outro",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "500 mg,1000 mg,500 mg,mg",
      "concentracao": "250 mg/5 ml|50",
      "intervalo": "8, 12",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 1"
    },
    {
      "nome": "Dip",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": ";60",
      "dose": "15,30,20,mg",
      "concentracao": "2.5 g/5 ml|500",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 1"
    },
    {
      "nome": "Testeconcentracoesvias",
      "condicao": "Infeção leve",
      "populacao": "",
      "via": "iv",
      "idade": "",
      "peso": "40;",
      "dose": "250 mg,500 mg,250 mg,mg",
      "concentracao": "250 mg/5 ml|50;500 mg/10 ml|50",
      "intervalo": "8",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Reconstituir com 5ml de água destilada [2] Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#ùltima nota#",
      "notas": "Manual de Teste, p. 2"
    },
    {
      "nome": "Testeconcentracoesvias",
      "condicao": "Infeção leve",
      "populacao": "",
      "via": "im",
      "idade": "",
      "peso": "40;",
      "dose": "250 mg,500 mg,250 mg,mg",
      "concentracao": "250 mg/5 ml|50;500 mg/10 ml|50",
      "intervalo": "8",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Reconstituir com 5ml de água destilada [2] Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#Reconstituir com 10ml de água destilada#",
      "notas": "Manual de Teste, p. 2"
    },
    {
      "nome": "Testeconcentracoesvias",
      "condicao": "Infeção grave",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "500 mg,1000 mg,500 mg,mg",
      "concentracao": "250 mg/5 ml|50;500 mg/10 ml|50",
      "intervalo": "6",
      "formula": "{#d/#c} ml",
      "adicionais": "#[1] Reconstituir com 5ml de água destilada [2] Reconstituir com 10ml de água destilada#",
      "notas": "Manual de Teste, p. 2"
    },
    {
      "nome": "Testeataquemanutencaodiferente",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "3;",
      "dose": "ataque(2.4 mg,2.4 mg,2.4 mg,mg/kg);manutencao(1.2 mg,1.2 mg,1.2 mg,mg/kg)",
      "concentracao": "60 mg/1 ml|60",
      "intervalo": "ataque(12, 8)",
      "formula": "{#p*#d_ataque/#c} ml {#p*#d_manutencao/#c} ml",
      "adicionais": "#@@Dose máxima diária: não exceder 4 administrações@#",
      "notas": "Manual de Teste, p. 3"
    },
    {
      "nome": "Testesoataque",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "ataque(1000 mg,1000 mg,1000 mg,mg);manutencao(1000 mg,1000 mg,1000 mg,mg)",
      "concentracao": "1 g/10 ml|100",
      "intervalo": "ataque(24);manutencao(24)",
      "formula": "{#d_ataque/#c} ml {#d_manutencao/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 4"
    },
    {
      "nome": "Testegravida",
      "condicao": "Infeção urinária",
      "populacao": "pediatrica",
      "via": "",
      "idade": "",
      "peso": "3;40",
      "dose": "25 mg,50 mg,30 mg,mg/kg",
      "concentracao": "2 g/10 ml|200",
      "intervalo": "12",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 5"
    },
    {
      "nome": "Testegravida",
      "condicao": "Infeção urinária",
      "populacao": "adulta",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "1000 mg,2000 mg,1000 mg,mg",
      "concentracao": "2 g/10 ml|200",
      "intervalo": "8",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 5"
    },
    {
      "nome": "Testegravida",
      "condicao": "Infeção urinária",
      "populacao": "gravida",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "500 mg,1000 mg,500 mg,mg",
      "concentracao": "2 g/10 ml|200",
      "intervalo": "12",
      "formula": "{#d/#c} ml",
      "adicionais": "#@@Ajustar em caso de insuficiência renal@#",
      "notas": "Manual de Teste, p. 5"
    },
    {
      "nome": "Testeuicompativel",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "1200000 UI,2400000 UI,1200000 UI,UI",
      "concentracao": "1000000 UI/10 ml|100000",
      "intervalo": "24*",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 6"
    },
    {
      "nome": "Testeuiconversao",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "500000 UI,1000000 UI,600000 UI,UI",
      "concentracao": "600 mg/5 ml|120",
      "intervalo": "12",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 7"
    },
    {
      "nome": "Testedoseinvariavel",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "3;40",
      "dose": "60 mg,60 mg,60 mg,mg/kg",
      "concentracao": "1 g/20 ml|50;",
      "intervalo": "12",
      "formula": "{#p*#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 8"
    },
    {
      "nome": "Testeintervalomultidia",
      "condicao": "",
      "populacao": "",
      "via": "",
      "idade": "",
      "peso": "40;",
      "dose": "2400000 UI,2400000 UI,2400000 UI,UI",
      "concentracao": "1 g/3.4 ml|294.118",
      "intervalo": "48",
      "formula": "{#d/#c} ml",
      "adicionais": "",
      "notas": "Manual de Teste, p. 9"
    },
    {
      "nome": "Testenotasmuitas",
      "condicao": "",
      "populacao": "gravida",
      "via": "iv",
      "idade": "",
      "peso": "40;",
      "dose": "200 mg,200 mg,200 mg,mg",
      "concentracao": "200 mg/1 ml|200;",
      "intervalo": "24*, 12",
      "formula": "{#d/#c} ml",
      "adicionais": "#@@Não administrar em bólus@#@@Monitorizar sinais de reação alérgica@#@@Não misturar com outros fármacos na mesma seringa@#@@Verificar função hepática antes da administração@#@@Contraindicado em caso de hipersensibilidade conhecida@#@@Ajustar em caso de insuficiência renal grave@#@@Manter o paciente em observação durante 30 minutos após a dose@#",
      "notas": "Manual de Teste, p. 10"
    }
  ]

  
};
